using CoreModels = Popo.Core.Contracts.Iss;
using Iss = Popo.HttpClients.Contracts.Iss;

namespace Popo.HttpClients.Common;

internal static class MoexContractMapper
{
    public static CoreModels.MoexBond ToContract(this Iss.MoexBond source) => new()
    {
        SecId = source.SecId,
        IssueName = source.IssueName,
        DisplayName = source.DisplayName,
        ShortName = source.ShortName,
        Isin = source.Isin,
        IssueDate = source.IssueDate,
        MatDate = source.MatDate,
        InitialFaceValue = source.InitialFaceValue,
        FaceUnit = source.FaceUnit,
        LatName = source.LatName,
        StartDateMoex = source.StartDateMoex,
        HasProspectus = source.HasProspectus,
        DecisionDate = source.DecisionDate,
        IsConcessionAgreement = source.IsConcessionAgreement,
        HasDefault = source.HasDefault,
        HasTechnicalDefault = source.HasTechnicalDefault,
        EmitentMismatchCur = source.EmitentMismatchCur,
        ListLevel = source.ListLevel,
        IncludedByMoex = source.IncludedByMoex,
        DaysToRedemption = source.DaysToRedemption,
        IssueSize = source.IssueSize,
        FaceValue = source.FaceValue,
        IsQualifiedInvestors = source.IsQualifiedInvestors,
        CouponFrequency = source.CouponFrequency,
        CouponDate = source.CouponDate,
        CouponPercent = source.CouponPercent,
        CouponValue = source.CouponValue,
        MorningSession = source.MorningSession,
        EveningSession = source.EveningSession,
        WeekendSession = source.WeekendSession,
        BondKind = source.BondKind,
        BondSubType = source.BondSubType,
        TypeName = source.TypeName,
        Group = source.Group,
        SecurityType = source.SecurityType,
        GroupName = source.GroupName,
        EmitterId = source.EmitterId,
        RegNumber = source.RegNumber,
        Name = source.Name,
        PrevPrice = source.PrevPrice,
        PrevWaPrice = source.PrevWaPrice,
        YieldAtPrevWaPrice = source.YieldAtPrevWaPrice,
        BoardId = source.BoardId,
        CurrencyId = source.CurrencyId,
        PrevTradeDate = source.PrevTradeDate,
        Accruedint = source.Accruedint,
        NextCouponDate = source.NextCouponDate,
        CouponPeriod = source.CouponPeriod,
        BuybackDate = source.BuybackDate,
        OfferDate = source.OfferDate,
        IssueSizePlaced = source.IssueSizePlaced,
        BondType = source.BondType,
        LotSize = source.LotSize,
        BoardName = source.BoardName,
        Status = source.Status,
        Decimals = source.Decimals,
        PrevLegalClosePrice = source.PrevLegalClosePrice,
        Remarks = source.Remarks,
        MarketCode = source.MarketCode,
        InstrId = source.InstrId,
        SectorId = source.SectorId,
        MinStep = source.MinStep,
        BuybackPrice = source.BuybackPrice,
        SecType = source.SecType,
        SettleDate = source.SettleDate,
        LotValue = source.LotValue,
        FaceValueOnSettleDate = source.FaceValueOnSettleDate,
        CallOptionDate = source.CallOptionDate,
        PutOptionDate = source.PutOptionDate,
        DateYieldFromIssuer = source.DateYieldFromIssuer,
    };

    public static CoreModels.MoexHistoryYields ToContract(this Iss.MoexHistoryYields source) => new()
    {
        BoardId = source.BoardId,
        TradeDate = source.TradeDate,
        SecId = source.SecId,
        NumTrades = source.NumTrades,
        Value = source.Value,
        Low = source.Low,
        High = source.High,
        Close = source.Close,
        LegalClosePrice = source.LegalClosePrice,
        AccInt = source.AccInt,
        WapPrice = source.WapPrice,
        YieldClose = source.YieldClose,
        Open = source.Open,
        Volume = source.Volume,
        MarketPrice2 = source.MarketPrice2,
        MarketPrice3 = source.MarketPrice3,
        Mp2ValTrd = source.Mp2ValTrd,
        MarketPrice3TradesValue = source.MarketPrice3TradesValue,
        MatDate = source.MatDate,
        Duration = source.Duration,
        YieldAtWap = source.YieldAtWap,
        IricpiClose = source.IricpiClose,
        BeiClose = source.BeiClose,
        CouponPercent = source.CouponPercent,
        CouponValue = source.CouponValue,
        BuybackDate = source.BuybackDate,
        LastTradeDate = source.LastTradeDate,
        FaceValue = source.FaceValue,
        CurrencyId = source.CurrencyId,
        CbrClose = source.CbrClose,
        YieldToOffer = source.YieldToOffer,
        YieldLastCoupon = source.YieldLastCoupon,
        OfferDate = source.OfferDate,
        FaceUnit = source.FaceUnit,
        TradingSession = source.TradingSession,
        CallOptionDate = source.CallOptionDate,
        CallOptionYield = source.CallOptionYield,
        CallOptionDuration = source.CallOptionDuration,
        PutOptionDate = source.PutOptionDate,
        DateYieldFromIssuer = source.DateYieldFromIssuer,
        TradeSessionDate = source.TradeSessionDate,
        ZSpread = source.ZSpread,
        ZSpreadAtWapPrice = source.ZSpreadAtWapPrice,
        BondType = source.BondType,
        BondSubType = source.BondSubType,
        ShortName = source.ShortName,
    };

    public static CoreModels.MoexMarketdataYields ToContract(this Iss.MoexMarketdataYields source) => new()
    {
        SecId = source.SecId,
        BoardId = source.BoardId,
        Price = source.Price,
        YieldDate = source.YieldDate,
        YieldDateType = source.YieldDateType,
        EffectiveYield = source.EffectiveYield,
        Duration = source.Duration,
        ZSpread = source.ZSpread,
        GSpread = source.GSpread,
        WaPrice = source.WaPrice,
        EffectiveYieldWaPrice = source.EffectiveYieldWaPrice,
        DurationWaPrice = source.DurationWaPrice,
        TradeMoment = source.TradeMoment,
        SeqNum = source.SeqNum,
    };

    public static CoreModels.MoexMarketdata ToContract(this Iss.MoexMarketdata source) => new()
    {
        SecId = source.SecId,
        BoardId = source.BoardId,
        Yield = source.Yield,
        Bid = source.Bid,
        Last = source.Last,
        LCurrentPrice = source.LCurrentPrice,
        MarketPrice2 = source.MarketPrice2,
        MarketPrice = source.MarketPrice,
        LClosePrice = source.LClosePrice,
        ClosePrice = source.ClosePrice,
        Duration = source.Duration,
        SysTime = source.SysTime,
    };

    public static CoreModels.MoexTrade ToContract(this Iss.MoexTrade source) => new()
    {
        TradeTime = source.TradeTime,
        Price = source.Price,
        Quantity = source.Quantity,
        Value = source.Value,
        Yield = source.Yield,
        BuySell = source.BuySell,
    };

    public static CoreModels.SecDescription ToContract(this Iss.SecDescription source) => new()
    {
        SecId = source.SecId,
        ShortName = source.ShortName,
        Name = source.Name,
        Isin = source.Isin,
        IsTraded = source.IsTraded,
        EmitentId = source.EmitentId,
        EmitentTitle = source.EmitentTitle,
        PrimaryBoardId = source.PrimaryBoardId,
        MarketPriceBoardId = source.MarketPriceBoardId,
    };

    public static CoreModels.MoexBondDescription ToContract(this Iss.MoexBondDescription source) => new()
    {
        SecId = source.SecId,
        IssueName = source.IssueName,
        Name = source.Name,
        ShortName = source.ShortName,
        RegNumber = source.RegNumber,
        Isin = source.Isin,
        IssueDate = source.IssueDate,
        MatDate = source.MatDate,
        InitialFaceValue = source.InitialFaceValue,
        FaceValue = source.FaceValue,
        FaceUnit = source.FaceUnit,
        LatName = source.LatName,
        StartDateMoex = source.StartDateMoex,
        HasProspectus = source.HasProspectus,
        DecisionDate = source.DecisionDate,
        IsConcessionAgreement = source.IsConcessionAgreement,
        HasDefault = source.HasDefault,
        HasTechnicalDefault = source.HasTechnicalDefault,
        ProgramRegistryNumber = source.ProgramRegistryNumber,
        EmitentMismatchCurrent = source.EmitentMismatchCurrent,
        ListLevel = source.ListLevel,
        DaysToRedemption = source.DaysToRedemption,
        IssueSize = source.IssueSize,
        IsQualifiedInvestors = source.IsQualifiedInvestors,
        CouponFrequency = source.CouponFrequency,
        NextCouponDate = source.NextCouponDate,
        CouponPercent = source.CouponPercent,
        CouponValue = source.CouponValue,
        MorningSession = source.MorningSession,
        EveningSession = source.EveningSession,
        WeekendSession = source.WeekendSession,
        RegistryDate = source.RegistryDate,
        BondType = source.BondType,
        BondSubType = source.BondSubType,
        TypeName = source.TypeName,
        Group = source.Group,
        Type = source.Type,
        GroupName = source.GroupName,
        EmitterId = source.EmitterId,
    };

    public static CoreModels.MoexEmitentDescription ToContract(this Iss.MoexEmitentDescription source) => new()
    {
        SecId = source.SecId,
        Id = source.Id,
        Title = source.Title,
        Inn = source.Inn,
        Okpo = source.Okpo,
        IsTraded = source.IsTraded,
    };

    public static CoreModels.MoexBondization.MoexBondCoupons ToContract(this Iss.MoexBondization.MoexBondCoupons source) => new()
    {
        Isin = source.Isin,
        SecId = source.SecId,
        CouponDate = source.CouponDate,
        StartDate = source.StartDate,
        InitialFaceValue = source.InitialFaceValue,
        FaceValue = source.FaceValue,
        FaceUnit = source.FaceUnit,
        Value = source.Value,
        ValuePercent = source.ValuePercent,
        ValueInRub = source.ValueInRub,
        BoardId = source.BoardId,
    };

    public static CoreModels.MoexBondization.MoexBondAmortizations ToContract(this Iss.MoexBondization.MoexBondAmortizations source) => new()
    {
        Isin = source.Isin,
        SecId = source.SecId,
        AmortDate = source.AmortDate,
        InitialFaceValue = source.InitialFaceValue,
        FaceValue = source.FaceValue,
        FaceUnit = source.FaceUnit,
        Value = source.Value,
        ValuePercent = source.ValuePercent,
        ValueInRub = source.ValueInRub,
        BoardId = source.BoardId,
    };

    public static CoreModels.MoexBondization ToContract(this Iss.MoexBondization source) => new()
    {
        Coupons = source.Coupons.Select(ToContract).ToList(),
        Amortizations = source.Amortizations.Select(ToContract).ToList()
    };
}
