// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Popo.Storage;

#nullable disable

namespace Popo.Storage.Migrations
{
    [DbContext(typeof(PopoDbContext))]
    [Migration("20260809214136_AddPortfolioValuationTiming")]
    partial class AddPortfolioValuationTiming
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Popo.Storage.Entities.BondRatingEntity", b =>
                {
                    b.Property<string>("Isin")
                        .HasColumnType("text");

                    b.Property<int?>("Acra")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Expert")
                        .HasColumnType("integer");

                    b.Property<int?>("NKR")
                        .HasColumnType("integer");

                    b.Property<int?>("NRA")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Isin");

                    b.ToTable("BondRatings");
                });

            modelBuilder.Entity("Popo.Storage.Entities.CurrencyRateEntity", b =>
                {
                    b.Property<DateOnly>("RateDate")
                        .HasColumnType("date");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Nominal")
                        .HasColumnType("double precision");

                    b.Property<double>("UnitRate")
                        .HasColumnType("double precision");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("RateDate", "CurrencyCode");

                    b.HasIndex("CurrencyCode");

                    b.ToTable("CurrencyRates");
                });

            modelBuilder.Entity("Popo.Storage.Entities.Moex.MoexAmortsEntity", b =>
                {
                    b.Property<string>("SecId")
                        .HasColumnType("text");

                    b.Property<DateOnly>("AmortDate")
                        .HasColumnType("date");

                    b.Property<string>("BoardId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FaceUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FaceValue")
                        .HasColumnType("double precision");

                    b.Property<double>("InitialFaceValue")
                        .HasColumnType("double precision");

                    b.Property<string>("Isin")
                        .HasColumnType("text");

                    b.Property<double?>("Value")
                        .HasColumnType("double precision");

                    b.Property<double?>("ValueInRub")
                        .HasColumnType("double precision");

                    b.Property<double?>("ValuePercent")
                        .HasColumnType("double precision");

                    b.HasKey("SecId", "AmortDate");

                    b.HasIndex("AmortDate")
                        .IsDescending();

                    b.ToTable("MoexAmortsEntities");
                });

            modelBuilder.Entity("Popo.Storage.Entities.Moex.MoexBondEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BondSubType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BondType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CouponFrequency")
                        .HasColumnType("integer");

                    b.Property<double?>("CouponPercent")
                        .HasColumnType("double precision");

                    b.Property<double>("CouponValue")
                        .HasColumnType("double precision");

                    b.Property<int?>("DaysToRedemption")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("DecisionDate")
                        .HasColumnType("date");

                    b.Property<int?>("EmitentMismatchCurrent")
                        .HasColumnType("integer");

                    b.Property<int?>("EmitterId")
                        .HasColumnType("integer");

                    b.Property<bool?>("EveningSession")
                        .HasColumnType("boolean");

                    b.Property<string>("FaceUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FaceValue")
                        .HasColumnType("double precision");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("HasDefault")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasProspectus")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasTechnicalDefault")
                        .HasColumnType("boolean");

                    b.Property<double?>("InitialFaceValue")
                        .HasColumnType("double precision");

                    b.Property<bool?>("IsConcessionAgreement")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsQualifiedInvestors")
                        .HasColumnType("boolean");

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("IssueName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("IssueSize")
                        .HasColumnType("bigint");

                    b.Property<string>("LatName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ListLevel")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("MatDate")
                        .HasColumnType("date");

                    b.Property<bool?>("MorningSession")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("NextCouponDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("OfferDate")
                        .HasColumnType("date");

                    b.Property<string>("ProgramRegistryNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("RegistryDate")
                        .HasColumnType("date");

                    b.Property<string>("SecId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("StartDateMoex")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("WeekendSession")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Isin");

                    b.HasIndex("SecId")
                        .IsUnique();

                    b.ToTable("MoexBonds");
                });

            modelBuilder.Entity("Popo.Storage.Entities.Moex.MoexBondSecurityEntity", b =>
                {
                    b.Property<string>("SecId")
                        .HasColumnType("text");

                    b.Property<string>("BoardId")
                        .HasColumnType("text");

                    b.Property<double?>("AccruedInt")
                        .HasColumnType("double precision");

                    b.Property<string>("BoardName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BondSubType")
                        .HasColumnType("text");

                    b.Property<string>("BondType")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("BuybackDate")
                        .HasColumnType("date");

                    b.Property<double?>("BuybackPrice")
                        .HasColumnType("double precision");

                    b.Property<DateOnly?>("CallOptionDate")
                        .HasColumnType("date");

                    b.Property<double?>("CouponPercent")
                        .HasColumnType("double precision");

                    b.Property<int>("CouponPeriod")
                        .HasColumnType("integer");

                    b.Property<double>("CouponValue")
                        .HasColumnType("double precision");

                    b.Property<string>("CurrencyId")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DateYieldFromIssuer")
                        .HasColumnType("date");

                    b.Property<int>("Decimals")
                        .HasColumnType("integer");

                    b.Property<string>("FaceUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FaceValue")
                        .HasColumnType("double precision");

                    b.Property<double?>("FaceValueOnSettleDate")
                        .HasColumnType("double precision");

                    b.Property<string>("InstrId")
                        .HasColumnType("text");

                    b.Property<string>("Isin")
                        .HasColumnType("text");

                    b.Property<long?>("IssueSize")
                        .HasColumnType("bigint");

                    b.Property<long?>("IssueSizePlaced")
                        .HasColumnType("bigint");

                    b.Property<string>("LatName")
                        .HasColumnType("text");

                    b.Property<int?>("ListLevel")
                        .HasColumnType("integer");

                    b.Property<long>("LotSize")
                        .HasColumnType("bigint");

                    b.Property<double?>("LotValue")
                        .HasColumnType("double precision");

                    b.Property<string>("MarketCode")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("MatDate")
                        .HasColumnType("date");

                    b.Property<double?>("MinStep")
                        .HasColumnType("double precision");

                    b.Property<DateOnly?>("NextCouponDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("OfferDate")
                        .HasColumnType("date");

                    b.Property<double?>("PrevLegalClosePrice")
                        .HasColumnType("double precision");

                    b.Property<double?>("PrevPrice")
                        .HasColumnType("double precision");

                    b.Property<DateOnly?>("PrevTradeDate")
                        .HasColumnType("date");

                    b.Property<double?>("PrevWaPrice")
                        .HasColumnType("double precision");

                    b.Property<DateOnly?>("PutOptionDate")
                        .HasColumnType("date");

                    b.Property<string>("RegNumber")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("SecName")
                        .HasColumnType("text");

                    b.Property<string>("SecType")
                        .HasColumnType("text");

                    b.Property<string>("SectorId")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("SettleDate")
                        .HasColumnType("date");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("YieldAtPrevWaPrice")
                        .HasColumnType("double precision");

                    b.HasKey("SecId", "BoardId");

                    b.ToTable("MoexBondSecurities");
                });

            modelBuilder.Entity("Popo.Storage.Entities.Moex.MoexCouponsEntity", b =>
                {
                    b.Property<string>("SecId")
                        .HasColumnType("text");

                    b.Property<DateOnly>("CouponDate")
                        .HasColumnType("date");

                    b.Property<string>("BoardId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FaceUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FaceValue")
                        .HasColumnType("double precision");

                    b.Property<double>("InitialFaceValue")
                        .HasColumnType("double precision");

                    b.Property<string>("Isin")
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<double?>("Value")
                        .HasColumnType("double precision");

                    b.Property<double?>("ValueInRub")
                        .HasColumnType("double precision");

                    b.Property<double?>("ValuePercent")
                        .HasColumnType("double precision");

                    b.HasKey("SecId", "CouponDate");

                    b.HasIndex("CouponDate")
                        .IsDescending();

                    b.ToTable("MoexCouponsEntities");
                });

            modelBuilder.Entity("Popo.Storage.Entities.Moex.MoexEmitentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Inn")
                        .HasColumnType("text");

                    b.Property<string>("Okpo")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MoexEmitents");
                });

            modelBuilder.Entity("Popo.Storage.Entities.Moex.MoexHistoryYieldsEntity", b =>
                {
                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date");

                    b.Property<string>("SecId")
                        .HasColumnType("text");

                    b.Property<string>("BoardId")
                        .HasColumnType("text");

                    b.Property<double?>("AccInt")
                        .HasColumnType("double precision");

                    b.Property<double?>("BeiClose")
                        .HasColumnType("double precision");

                    b.Property<string>("BondSubType")
                        .HasColumnType("text");

                    b.Property<string>("BondType")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("BuybackDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("CallOptionDate")
                        .HasColumnType("date");

                    b.Property<double?>("CallOptionDuration")
                        .HasColumnType("double precision");

                    b.Property<double?>("CallOptionYield")
                        .HasColumnType("double precision");

                    b.Property<double?>("CbrClose")
                        .HasColumnType("double precision");

                    b.Property<double?>("Close")
                        .HasColumnType("double precision");

                    b.Property<double>("CouponPercent")
                        .HasColumnType("double precision");

                    b.Property<double>("CouponValue")
                        .HasColumnType("double precision");

                    b.Property<string>("CurrencyId")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DateYieldFromIssuer")
                        .HasColumnType("date");

                    b.Property<double?>("Duration")
                        .HasColumnType("double precision");

                    b.Property<string>("FaceUnit")
                        .HasColumnType("text");

                    b.Property<double>("FaceValue")
                        .HasColumnType("double precision");

                    b.Property<double?>("High")
                        .HasColumnType("double precision");

                    b.Property<double?>("IricpiClose")
                        .HasColumnType("double precision");

                    b.Property<DateOnly?>("LastTradeDate")
                        .HasColumnType("date");

                    b.Property<double?>("LegalClosePrice")
                        .HasColumnType("double precision");

                    b.Property<double?>("Low")
                        .HasColumnType("double precision");

                    b.Property<double?>("MarketPrice2")
                        .HasColumnType("double precision");

                    b.Property<double?>("MarketPrice3")
                        .HasColumnType("double precision");

                    b.Property<double?>("MarketPrice3TradesValue")
                        .HasColumnType("double precision");

                    b.Property<DateOnly?>("MatDate")
                        .HasColumnType("date");

                    b.Property<double?>("Mp2ValTrd")
                        .HasColumnType("double precision");

                    b.Property<double?>("NumTrades")
                        .HasColumnType("double precision");

                    b.Property<DateOnly?>("OfferDate")
                        .HasColumnType("date");

                    b.Property<double?>("Open")
                        .HasColumnType("double precision");

                    b.Property<DateOnly?>("PutOptionDate")
                        .HasColumnType("date");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("TradeSessionDate")
                        .HasColumnType("date");

                    b.Property<int?>("TradingSession")
                        .HasColumnType("integer");

                    b.Property<double?>("Value")
                        .HasColumnType("double precision");

                    b.Property<double?>("Volume")
                        .HasColumnType("double precision");

                    b.Property<double?>("WapPrice")
                        .HasColumnType("double precision");

                    b.Property<double?>("YieldAtWap")
                        .HasColumnType("double precision");

                    b.Property<double?>("YieldClose")
                        .HasColumnType("double precision");

                    b.Property<double?>("YieldLastCoupon")
                        .HasColumnType("double precision");

                    b.Property<double?>("YieldToOffer")
                        .HasColumnType("double precision");

                    b.Property<double?>("ZSpread")
                        .HasColumnType("double precision");

                    b.Property<double?>("ZSpreadAtWapPrice")
                        .HasColumnType("double precision");

                    b.HasKey("TradeDate", "SecId", "BoardId");

                    b.HasIndex("SecId", "BoardId", "TradeDate");

                    b.ToTable("MoexHistoryYieldsEntities");
                });

            modelBuilder.Entity("Popo.Storage.Entities.Moex.SecInfoEntity", b =>
                {
                    b.Property<string>("SecId")
                        .HasColumnType("text");

                    b.Property<int?>("EmitentId")
                        .HasColumnType("integer");

                    b.Property<string>("EmitentTitle")
                        .HasColumnType("text");

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarketPriceBoardId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryBoardId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SecId");

                    b.ToTable("ActiveSecEntities");
                });

            modelBuilder.Entity("Popo.Storage.Entities.PortfolioCashFlowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Amount")
                        .HasPrecision(20, 6)
                        .HasColumnType("double precision");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("PortfolioCashFlows");
                });

            modelBuilder.Entity("Popo.Storage.Entities.PortfolioValuationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Timing")
                        .HasColumnType("integer");

                    b.Property<double>("TotalValue")
                        .HasPrecision(20, 6)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Timing")
                        .IsUnique();

                    b.ToTable("PortfolioValuations");
                });
#pragma warning restore 612, 618
        }
    }
}
